name: miniclams workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install libbsd-dev

    - name: Build
      run: make

    - name: test
      run: make tests

    - name: Upload log file
      uses: actions/upload-artifact@v2
      with:
        name: log-file
        path: logfile.log
